In [28]:
# defining the required libraries 
import numpy as np
from queue import Queue

In [29]:
class Graph:                                                                    # creating a class Graph used for converting an image to a graph with V values

  def __init__(self,no_of_nodes,Node_location,directed=True):                   # defining the constructor
    self.no_of_nodes = no_of_nodes
    self.Node_location = Node_location
    self.directed = directed
    self.m_adj_list = {node: set() for node in self.Node_location}

  def add_edge(self,node1, node2, weight=1):                                    # function for adding weight = 1 to the edges of the graph
    self.m_adj_list[node1].add((node2, weight))
    if not self.directed:
      self.m_adj_list[node2].add((node1, weight))

  def print_adj_list(self):                                                     # printing the graph like structure of the given image for V
      for key in self.m_adj_list.keys():
        print("node", key, ": ", self.m_adj_list[key])

  def bfs(self, start_node, target_node):                                       # defining the Breadth First Search (BFS) algorithm
    # Set of visited nodes to prevent loops
    visited = set()
    queue = Queue()

    # Add the start_node to the queue and visited list
    queue.put(start_node)
    visited.add(start_node)
    
    # start_node has not parents
    parent = dict()
    parent[start_node] = None

    # Perform step 3
    path_found = False
    while not queue.empty():
        current_node = queue.get()
        if current_node == target_node:
            path_found = True
            break

        for (next_node, weight) in self.m_adj_list[current_node]:
            if next_node not in visited:
                queue.put(next_node)
                parent[next_node] = current_node
                visited.add(next_node)
                
    # Path reconstruction
    path = []
    if path_found:
        path.append(target_node)
        while parent[target_node] is not None:
            path.append(parent[target_node]) 
            target_node = parent[target_node]
        path.reverse()
    return path



In [30]:
## User defined functions that are used in the code search(), length_of_Shortest_path(), adjacency_4(), target_neighbor4()

def search(loc):                                                                # searching the location of the pixel value from the list of pixel values where the nodes exist
  l =len(Node_location)
  for i in range(l):
    if loc == Node_location[i]:
      return int(i)


def length_of_Shortest_path(path,path_type):                                    # printing the shortest path and its length for all the three path types
  l = len(path)
  if path_type ==1:
    t = '4-adjacency path'
    if l==0:
      print("No path exist between the source and the target pixels with " + t )
    else:
      print("The shortest path between the source and the target pixels with " + t + " is: ", path)
      print("The length of the shortest path with " + t + " is: ",len(path)-1)
      
  elif path_type ==2:
    t = '8-adjacency path'
    if l==0:
      print("No path exist between the source and the target pixels with " + t )
    else:
      print("The shortest path between the source and the target pixels with " + t + " is: ", path)
      print("The length of the shortest path with " + t + " is: ",len(path)-1)
    
  elif path_type ==3:
    t = 'm-adjacency path'
    if l==0:
      print("No path exist between the source and the target pixels with " + t )
    else:
      print("The shortest path between the source and the target pixels with " + t + " is: ", path)
      print("The length of the shortest path with " + t + " is: ",len(path)-1)
  



def adjacency_4(Node,Node_location,p_r,p_c):                                    # finding the 4-adjacency of pixels in an image
  padded_Node = np.pad(Node,pad_width = 1)                                      # zero padded the image element
  visit = []                                                                    # created an array for storing the visited pixel
  Q = [(p_r,p_c)]                                                               # queue from which the pixel locations are fetched
  while len(Q)>0: 
    r = Q[0][0]                                                                 # we start with the start pixel that is given as the input
    c = Q[0][1]
    pixel_loc = (r,c)
    loc_start_node = search(pixel_loc)
    if pixel_loc not in visit:                                                  
      r_sweep = [-1,1,0,0]
      c_sweep = [0,0,1,-1]
      for i in range(0,4):
        r_1 = r+1                                                               # mapping the values of the non padded matrix to the zero padded matrix
        c_1 = c+1
        if (padded_Node[r_1+(r_sweep[i])][c_1+(c_sweep[i])]==1):                # considers all the pixels that satisfy the 4-adjacency condition with values that sastisfy V
          loc = (r+(r_sweep[i]),c+(c_sweep[i]))
          Q.append(loc)
          a = search(loc)
          G.add_edge(Node_location[loc_start_node],Node_location[a])            # the nodes that satisfy the conditions will be joined using an edge with weight = 1
        else:
          continue
    Q.pop(0)                                                                    # pops off the value that was searched (visited) from the queue
    visit.append(pixel_loc)                                                     # appends the nodes to the queue for checking 
  path = G.bfs(start_node,target_node)                                          # using the bfs() for finding the shortest path between the 2 pixels
  return path




def target_neighbor4(r,c):                                                      # finding the 4-adjacency of a single pixel
  padded_Node = np.pad(Node,pad_width = 1)
  adj4 = []
  r_s = [-1,1,0,0]
  c_s = [0,0,1,-1]
  r_1 = r+1
  c_1 = c+1
  for x in range(0,4):
    if (padded_Node[r_1+r_s[x]][c_1+c_s[x]]) is None:
      pass
    else: 
      adj4.append((r + r_s[x] , c + c_s[x]))
  return adj4

In [31]:
# Defining the Image_Array
Img_row = int(input("Enter the number of Rows in the Image: "))
Img_column = int(input("Enter the number of Columns in the Image: "))
Image_ele = np.zeros((Img_row,Img_column), dtype = 'int32')
for i in range(Img_row):
  for j in range(Img_column):
    Image_ele[i][j] = int(input())
Image_Array = np.array(Image_ele)
 
 
 
# Defining the value of V
Int_Val = int(input("Enter the number of Intensity Values to be defined in V: "))
V = []
for x in range(0,Int_Val):
  Val = int(input())
  V.append(Val)
V = np.array(V, dtype='int32')
 
 
 
 
# Defining the path_type
print("Choose the path type from the below options (1/2/3)")
path_type = int(input("1. 4-path\n2. 8-path\n3. m-path\nEnter the choice:1 "))
 
 
 
 
# Defining the p and q location
p_r = int(input("Enter the row number of the starting pixel: "))
p_c = int(input("Enter the column number of the starting pixel: ")) 
q_r = int(input("Enter the row number of the destination pixel: "))
q_c = int(input("Enter the column number of the destination pixel: "))
start_node = (p_r,p_c)
target_node = (q_r,q_c)
 
 
print("\n\n")
print("The Image element is:\n" , Image_Array)
print("The defined value of V is: ", V)
print("The source pixel location is: ", start_node)
print("The target pixel location is: ", target_node)
print("The chosen path type is: ", path_type)
 
 
 
Node = np.zeros((Img_row,Img_column), dtype = 'int32')                          # the approach converts that values in the given iamge element that is equal to V to 1 (which are considered as the nodes of the graph) and the others to 0 to form a binary matrix
Node_location = []
no_of_nodes = 0
for i in range(Img_row):
  for j in range(Img_column):
    if Image_Array[i][j] in V:
      Node[i][j] = 1
      Node_location.append((i,j))
      no_of_nodes = no_of_nodes + 1
    else:
      Node[i][j] = 0
 
      
G = Graph(no_of_nodes,Node_location,directed=False)                             # calls the class GRAPH to construct the graph relation between the nodes of the image found in the above step



Enter the number of Rows in the Image: 6
Enter the number of Columns in the Image: 6
1
3
3
3
3
2
4
3
2
1
3
1
1
1
0
0
2
2
0
2
0
0
1
0
5
5
0
2
5
1
1
2
3
4
5
0
Enter the number of Intensity Values to be defined in V: 3
1
3
2
Choose the path type from the below options (1/2/3)
1. 4-path
2. 8-path
3. m-path
Enter the choice:1 2
Enter the row number of the starting pixel: 3
Enter the column number of the starting pixel: 4
Enter the row number of the destination pixel: 3
Enter the column number of the destination pixel: 1



The Image element is:
 [[1 3 3 3 3 2]
 [4 3 2 1 3 1]
 [1 1 0 0 2 2]
 [0 2 0 0 1 0]
 [5 5 0 2 5 1]
 [1 2 3 4 5 0]]
The defined value of V is:  [1 3 2]
The source pixel location is:  (3, 4)
The target pixel location is:  (3, 1)
The chosen path type is:  2


In [32]:
# working for the different path_types :: 4-adjacency, 8-adjacency and m-adjacecny

if (path_type == 1):                                                            # for 4-adjacency, we call the function written for the same 
  path = adjacency_4(Node,Node_location,p_r,p_c)
  length_of_Shortest_path(path,path_type)
  



elif (path_type == 2):                                                          # for 8-adjacency, we have the similar approach same as the 4-adjacency. here we consider all the 8 neighboring pixels and then follows the same process of using the visited and queue arrays
    padded_Node = np.pad(Node,pad_width = 1)
    visit = []
    Q = [(p_r,p_c)]
    while len(Q)>0: 
      r = Q[0][0]
      c = Q[0][1]
      pixel_loc = (r,c)
      loc_start_node = search(pixel_loc)
      if pixel_loc not in visit:
        r_sweep = [-1,0,1,-1,1,-1,0,1]
        c_sweep = [-1,-1,-1,0,0,1,1,1]
        for i in range(0,8):
          r_1 = r+1     
          c_1 = c+1
          if (padded_Node[r_1+(r_sweep[i])][c_1+(c_sweep[i])]==1):
            loc = (r+(r_sweep[i]),c+(c_sweep[i]))
            Q.append(loc)
            a = search(loc)
            G.add_edge(Node_location[loc_start_node],Node_location[a])
          else:
            continue
      Q.pop(0)
      visit.append(pixel_loc)
    path = G.bfs(start_node,target_node)
    length_of_Shortest_path(path,path_type)


elif (path_type == 3):                                                          # for m-adjacency
      path = adjacency_4(Node,Node_location,p_r,p_c)                            # first call the 4-adjacency function to check whether we are able to reach the final pixel with the 4-adjacency criteria
      padded_Node = np.pad(Node,pad_width = 1)
      if len(path)==0:                                                          # if no, then we compare the diagonal elements
        D_ele = []                                          
        pixel_loc = (q_r,q_c)                                                   # process :: taking the diagonal elements of target, check if any of the diagonal corresponds to any of the pixel locations in node_location. if yes creates an edge between the same
        r_sweep = [-1,1,-1,1]
        c_sweep = [-1,1,1,-1]
        for i in range(0,4):
          r_1 = q_r+1    
          c_1 = q_c+1
          if (padded_Node[r_1+(r_sweep[i])][c_1+(c_sweep[i])] == 1):            
            loc = (q_r+(r_sweep[i]),q_c+(c_sweep[i]))
            D_ele.append(loc)                                                   # creates an array of diagonal elements that satisfy V 
        for j in range(len(Node_location)):                         
          if Node_location[j] in D_ele:                                         # compares the diagonal elements array with the exisitng node locations 
            t_adj4 = target_neighbor4(q_r,q_c)                                  # finding the adjacency of the target pixel
            t_r = Node_location[j][0]
            t_c = Node_location[j][1]
            temp_adj4 = target_neighbor4(t_r,t_c)                               # finding the adjacency of the neighbor pixel to target
            inter_Section = list(set(t_adj4).intersection(set(temp_adj4)))      # finds the intersection of the 4-neighbor pixels
            for x in range(len(inter_Section)):
              row_val = inter_Section[x][0]
              column_val = inter_Section[x][1]
              tar_loc = search(target_node)
              if Node[row_val][column_val] == 0:                                # checks if the values of the intersecting pixels does not lie in V
                for z in D_ele:
                  re_loc = search(z)
                  G.add_edge(Node_location[tar_loc],Node_location[re_loc])      # if yes, forms an edge between the 2 pixels with weight = 1
              else: 
                pass
        path = G.bfs(start_node,target_node)                                    
        length_of_Shortest_path(path,path_type)  
      else:
        length_of_Shortest_path(path,path_type)


else:
    print("Invalid Entry")                                                      # if the path_type variable gets a value other than the 3 mentioned


The shortest path between the source and the target pixels with 8-adjacency path is:  [(3, 4), (2, 4), (1, 3), (1, 2), (2, 1), (3, 1)]
The length of the shortest path with 8-adjacency path is:  5
